version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    image: lizzardmedeiros/laravel-app
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ./application:/application
    ports:
      - "8000:8000"
    networks:
      - laravel
networks:
  laravel:
    driver: bridge